# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /Posts/:year/:month/:day/:title

# Shows events with dates in the future
future: true

# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
date_format: "%b %-d, %Y"

exclude: [".gitignore", "CNAME", "README.md", "Gemfile"]
highlighter: rouge

# Build settings
markdown: kramdown

title : 8-Bit Labs
tagline: 8-Bit Labs
description: Experiments with 8-Bit development, hardware and games.
author :
  name : Rob Prouse
  email : rob@8bitlabs.ca
  github : 8-bitlabs
  twitter : rprouse
#  feedburner : feedname

# This is used in the Atom & RSS feeds and in the sitemap
production_url: https://8bitlabs.ca
rss_path: /rss.xml
atom_path: /atom.xml
host: 0.0.0.0

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 8

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

autopages:
  enabled: true

  # Collection pages, omit to disable
  collections:
    enabled: false

  # Tag pages, omit to disable
  tags:
    layouts:
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tags/:tag'
    silent: false
    slugify:
      mode: 'default'   # :tag is slugified.
      case: false